# Testing Masking Logic to Ignore Padding

In [70]:
import numpy as np
# print the array with 2 decimal places
np.set_printoptions(precision=2)

# Generate a random 2D array
np.random.seed(0)
a = np.random.rand(3, 5)
a

array([[0.55, 0.72, 0.6 , 0.54, 0.42],
       [0.65, 0.44, 0.89, 0.96, 0.38],
       [0.79, 0.53, 0.57, 0.93, 0.07]])

In [71]:
# Add 2 columns to the array and fill them with zeros
b = np.zeros((3, 2))
c = np.concatenate((a, b), axis=1)
c

array([[0.55, 0.72, 0.6 , 0.54, 0.42, 0.  , 0.  ],
       [0.65, 0.44, 0.89, 0.96, 0.38, 0.  , 0.  ],
       [0.79, 0.53, 0.57, 0.93, 0.07, 0.  , 0.  ]])

In [72]:
# Generate a mask with 1s and 0s for the non padded columns of the array
mask = np.ones((3, 5+2), dtype=float)
mask[:, -2:] = 0
print(f"Mask:\n{mask} \nshape: {mask.shape}")

Mask:
[[1. 1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 1. 0. 0.]] 
shape: (3, 7)


In [73]:
# Calculate the number of non-padded columns using the only the mask matrix
non_padded_columns = np.sum(mask == 1) / mask.shape[0]
non_padded_columns

np.float64(5.0)

In [74]:
# Create a new masks with all ones for now
masks = np.ones((3, 5+2), dtype=float)
# Make a variable called masks that has an additional dimension in the beginning of size 2
# So 4 x 7 x 3, where 4 is batch size and 7 is columns and 3 is rows
masks = np.expand_dims(masks, 0)
masks = np.repeat(masks, 4, axis=0)
# edit the masks of different batch elements
masks[0][:, -2:] = 0
masks[1][:, -1] = 0
masks[2][:, -3:] = 0

print(f"Masks:\n{masks} \nshape: {masks.shape}")

Masks:
[[[1. 1. 1. 1. 1. 0. 0.]
  [1. 1. 1. 1. 1. 0. 0.]
  [1. 1. 1. 1. 1. 0. 0.]]

 [[1. 1. 1. 1. 1. 1. 0.]
  [1. 1. 1. 1. 1. 1. 0.]
  [1. 1. 1. 1. 1. 1. 0.]]

 [[1. 1. 1. 1. 0. 0. 0.]
  [1. 1. 1. 1. 0. 0. 0.]
  [1. 1. 1. 1. 0. 0. 0.]]

 [[1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]]] 
shape: (4, 3, 7)


In [75]:
# Calculate the number of non-padded columns for each batch element using the variable of dimension: batch size x rows x columns
non_padded_columns = np.sum(masks == 1, axis=(1, 2)) / masks.shape[1]
non_padded_columns

array([5., 6., 4., 7.])

In the case of GRU network, the `non-padded_columns` variable can be used a `variable_sequence_length` variable that is passed to the forward function to ignore the padded values. This way loss won't be calculated for the padded values as the padded values aren't forwarded to the model in the first place.

Also when comparing this example to dmatrix masks, the `masks.shape[1]` contains the octave bands dimension so that is what you have to divide the sum of all 1s in the mask matrix with. This gives the number of time frames that are not padded.

In [76]:
# Initialize the loss array with random number
loss = np.random.rand(3, 5+2)
print(f"Loss array:\n{loss}")

Loss array:
[[0.09 0.02 0.83 0.78 0.87 0.98 0.8 ]
 [0.46 0.78 0.12 0.64 0.14 0.94 0.52]
 [0.41 0.26 0.77 0.46 0.57 0.02 0.62]]


In [77]:
# Multiply loss by masks
loss = loss * masks
print(f"Loss array after multiplication:\n{loss}")

# loss = (loss * masks.mean(dim=2)).sum() / masks.sum() # This is how it is done in train.py for GRU

Loss array after multiplication:
[[[0.09 0.02 0.83 0.78 0.87 0.   0.  ]
  [0.46 0.78 0.12 0.64 0.14 0.   0.  ]
  [0.41 0.26 0.77 0.46 0.57 0.   0.  ]]

 [[0.09 0.02 0.83 0.78 0.87 0.98 0.  ]
  [0.46 0.78 0.12 0.64 0.14 0.94 0.  ]
  [0.41 0.26 0.77 0.46 0.57 0.02 0.  ]]

 [[0.09 0.02 0.83 0.78 0.   0.   0.  ]
  [0.46 0.78 0.12 0.64 0.   0.   0.  ]
  [0.41 0.26 0.77 0.46 0.   0.   0.  ]]

 [[0.09 0.02 0.83 0.78 0.87 0.98 0.8 ]
  [0.46 0.78 0.12 0.64 0.14 0.94 0.52]
  [0.41 0.26 0.77 0.46 0.57 0.02 0.62]]]


In [78]:
# Review variables
print(f"non_padded_columns:\n{non_padded_columns} \nshape: {non_padded_columns.shape}")

# Create a variable that contains input in the dimension of batch size x rows x columns in this case 4 x 3 x 7
input = np.random.rand(4, 3, 5+2)
# print(f"Input array:\n{input}")
print(f"Input array shape:\n{input.shape}")

# Use the non_padded_columns variable to remove the padding from the input variable for each batch element
# Remember that now the columns dimension will have different size for each batch element (maybe use torch tensor for this)
#TODO -  Can't figure out how to do this

# print(f"Input array after removing padding:\n{input}")
print(f"Input array shape after removing padding:\n{input.shape}")


non_padded_columns:
[5. 6. 4. 7.] 
shape: (4,)
Input array shape:
(4, 3, 7)
Input array shape after removing padding:
(4, 3, 7)


## Something about packing and unpacking sequences

In [79]:
import torch

# Convert input and mask to PyTorch tensors
input_tensor = torch.tensor(input, dtype=torch.float32)  # Shape: (batch_size, rows, cols)
print(f"Input tensor shape: {input_tensor.shape}")
mask_tensor = torch.tensor(masks, dtype=torch.float32)  # Shape: (batch_size, rows, cols)
print(f"Mask tensor shape: {mask_tensor.shape}")

# Compute the number of non-padded time steps per batch element (sum along time axis)
non_padded_lengths = torch.sum(mask_tensor[:, 0, :] == 1, dim=1)  # Shape: (batch_size,)

print(f"Non-padded time steps per batch: {non_padded_lengths}")

# Permute input to (batch, sequence_length, feature_dim) for GRU compatibility
input_tensor = input_tensor.permute(0, 2, 1)  # Shape: (batch_size, sequence_length, feature_dim)
print(f"Input tensor shape after permutation: {input_tensor.shape}")

# Pack sequences for GRU
packed_input = torch.nn.utils.rnn.pack_padded_sequence(
    input_tensor, non_padded_lengths.cpu(), batch_first=True, enforce_sorted=False
)

print(f"Packed input: {packed_input.data}")
print(f"Packed input data: {packed_input.data.shape}")
print(f"Packed input batch_sizes: {packed_input.batch_sizes}")


Input tensor shape: torch.Size([4, 3, 7])
Mask tensor shape: torch.Size([4, 3, 7])
Non-padded time steps per batch: tensor([5, 6, 4, 7])
Input tensor shape after permutation: torch.Size([4, 7, 3])
Packed input: tensor([[0.0047, 0.5920, 0.2974],
        [0.2533, 0.1966, 0.4687],
        [0.6121, 0.0602, 0.5702],
        [0.2961, 0.2654, 0.1318],
        [0.6778, 0.5723, 0.8138],
        [0.4663, 0.3687, 0.9768],
        [0.6169, 0.6668, 0.4386],
        [0.1187, 0.5232, 0.7163],
        [0.2700, 0.2231, 0.3965],
        [0.2444, 0.8210, 0.6048],
        [0.9437, 0.6706, 0.9884],
        [0.3180, 0.0939, 0.2894],
        [0.7352, 0.9527, 0.8811],
        [0.1590, 0.0971, 0.7393],
        [0.6818, 0.2104, 0.1020],
        [0.4143, 0.5759, 0.1832],
        [0.9622, 0.4471, 0.5813],
        [0.1104, 0.8379, 0.0392],
        [0.3595, 0.1289, 0.2089],
        [0.2488, 0.8464, 0.8817],
        [0.6563, 0.0961, 0.2828],
        [0.5762, 0.6995, 0.6925]])
Packed input data: torch.Size([22, 3])
P